[DOCS] Align with new TYPO3 documentation standards
FriendsOfTYPO3/dbal pull request #9
Opened 2022-04-02 08:48 UTC by alexander-nitsche

Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/182

2022-04-02 08:50 UTC, alexander-nitsche commented
This is how it looks like:
![Screen Shot 2022-04-02 at 10 49 23](https://user-images.githubusercontent.com/20297232/161375383-472c8f44-819b-4fab-a247-bead148b4684.png)

2022-04-08 14:02 UTC, alexander-nitsche commented
Added two new commits regarding badges in README and additional sources (TER, repository and docs.typo3.org) in composer.json.

In addition, the TER homepage is missing the "Code Insights", "Found an issue?" and "Packagist" buttons, which seem to be caused by the empty "Link to repository", "Link to issue tracker", "Composer name of extension" fields in the TER extension edit form.

Relates: TYPO3-Documentation/T3DocTeam#185

2022-04-20 12:37 UTC, ohader requested changes
Avoid author pointing...

2022-04-20 12:37 UTC, ohader commented on Documentation/Contribution/Index.rst
> +contact `Benni Mack`_ for any questions regarding "dbal".
Please avoid pointing to Benni here, refer to the issue tracker instead...
(seems that basically all legacy extensions had that, I wonder why...)

2022-04-20 12:39 UTC, ohader commented
Styles CI & Travis CI did not respond back, probably can be dropped (at least Travis)

2022-04-21 11:30 UTC, alexander-nitsche commented on Documentation/Contribution/Index.rst
> +contact `Benni Mack`_ for any questions regarding "dbal".
Done.

2022-04-21 11:35 UTC, ohader approved these changes

2022-04-21 11:35 UTC, merged

2022-04-21 11:36 UTC, ohader commented
TER foo done